name: CI

on: push

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ruff lint
        uses: chartboost/ruff-action@v1
        continue-on-error: true
      - name: Ruff format
        uses: chartboost/ruff-action@v1
        with:
          args: "format --check"
